FROM python:3.9-buster

WORKDIR /opt/flaskr

ARG ENVIRONMENT

ENV FLASK_ENV=${ENVIRONMENT}

ENV FLASK_APP=flaskr

COPY . .

RUN pip install -r requirements.txt 

EXPOSE 5000

ENTRYPOINT /opt/flaskr/deployments/flask/flaskr-init.sh
