"""empty message

Revision ID: da5e1ae5287a
Revises: 4ecef9945226
Create Date: 2020-12-18 12:29:06.579469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5e1ae5287a'
down_revision = '4ecef9945226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bgcolor', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bgcolor')
    # ### end Alembic commands ###
